Table student {
    __ __
    interested_tags array_of_string // array of tag in interest of this student
    owned_progarms  array_of_owned_progarm_item // might not need progarm that is  owned by this student
    wishlist array_of_wish_item // wishlist of this studednt
    basket array_of_basket_item // basket ( list of progarm to be bought) of this studednt
    payment_method what // what
 }

Table teacher {
    __ __
    owned_progarms  array_of_owned_progarm_item // progarm that is owned by this teacher

 }

 Table courses {
    _id objectId 
    name string // course name
    description string // long description in md?
    course_objective array_of_string
    course_requirement string
    difficulty_level string
    tags array_of_objectId // course's tag in array of tag_id
    course_pic string // pic in course profile in URL may need more
    created_date date
    total_video_length int // in second
    chapter_count int
    quiz_count int
    file_count int
    student_count int // number of student who enroll this course
    teacher_id objectId
    rating double // average review score of this course
    review_count int // number of review
    price double // of a course in baht
    status string // finished | not started | started | private
 }

  Table classes {
    _id objectId // class's id
    name string
    description string // long description
    class_objective array_of_string // list of class_objective
    class_requirement string
    difficulty_level string
    tags array_of_objectId // class's tag in array of tag_id
    class_pic string
    created_date date
    student_count int
    max_student int
    assignment_count int
    meeting_count int
    chapter_count int
    open_time something
    registration_ended_date date // can't register beyond this date
    class_ended_date date // the day class end and no more teaching
    teacher_id objectId // may include name
    price double // of a course in baht
    status string // finished | not started | started | private
 }

  Table chapters {
    _id objectId // chapter's id
    course_id objectId
    name string // chapter's name
    description string
    chapter_num int // chapter number
    lesson_count int // total lesson count
    chapter_length int // expected study time of this chapter in second (video included)
    

 }
 

 Table pre_quiz {
    quiz_id objectId
    
 }
  Table quiz {
    quiz_id objectId
    quiz_struct quiz_struct

 }

  Table course_progresses { // not done yet
    _id objectId
    student_id objectId
    course_id objectId //
    progress double // total progress in percent
    finished boolean // has student finished this course
    lessons array_of_lesson_progress
 }
 Table lesson_progress { // not done yet
    __ __
    lesson_id objectId
    chapter_id objectId
    finished boolean //  has student finished this lessson
    lesson_completed int //  lesson lenght completed in second
    quiz_score int_or_double // absolute score or percent for quiz only

 }


   Table class_progresses { // not done yet
    _id objectId
    student_id objectId
    progarm_id objectId // class or course id determine by type
    type string // course and class
    finished boolean
    and_more_for_course more // look like course+chapter+lesson
 }
 Table post {
    _id objectId
    class_id objectId
    teacher_id objectId // writer
    name string
    text string
    last_edit date
    comments array_of_comment
    attachments array_of_attached_file
 }
  Table attached_file {
    __ __
    attachment_type string // doc video or more
    src string // URL of the file
 }
Table attached_file2 {
    __ __
    attachment_type string // doc video or more
    src string // URL of the file
 }
 Table assignment {
    _id objectId
    class_id objectId
    name string
    description string
    created_date date
    due_date date
    attachments array_of_attached_file

 }

Table basket_item {
    __ __
    basket_item_id objectId
    progarm_id objectId // class_id or course_id of the item in basket
    type string // class or course
   
 }
 Table transaction {
    _id objectId
    user_id objectId //buyer
    purchase_time date
    total_price double
    purchase_list array_of_purchase_item
 }
 Table purchase_item {
  __ __
  progarm_id objectId // class or course id determine by type
  type string // class or course
  price double
}
 Table review {
    _id objectId
    course_id objectId
    score int
    description string
 }
 Table comment {
  __ __
  _id objectId
  user_id objectId // writer
  created_date date
  description string
}
Table owned_progarm_item {
  __ __
  progarm_id objectId // class or course id determine by type
  type string // class or course
}

Table users {
  _id objectId //
  username string
  password string
  email string
  full_name string
  proflie_pic string // user profile picture in URL
  config object(config) // user's configuration
  type string // student or teacher
}
Table config {
  theme str // light or dark theme for website
}

Table wishlist_item {
  __ __
  wishlist_item_id objectId
  progarm_id objectId // class or course id determine by type
  
  type string // class or course

  
}
Table announcement {
  _id objectId
  course_id objectId // anuncement owner
  teacher_id objectId // writer's teacher_id 
  last_edit date
  name str
  text string // announcement info text
  attachments array_of_attached_file // file attachments
}
Table lesson {
  __ __
  _id objectId // lessin's id
  course_id objectId
  chapter_id objectId
  lesson_num int // for lesson ordering
  name string // lesson name
  description string
  lesson_type string // video,doc,quiz
  lesson_length int // expected study time of this lesson in second (video included)
}
Table video {
  __ __
  src string // URL of the file
}
Table doc {
  __ __
  src string // URL of the file
}

Table achievements {
  __ __ // wah==
}
Table tags {
  __ __
  _id objectId
  name string
}

Ref: "courses"."teacher_id" < "teacher"."__"

Ref: "classes"."_id" < "post"."_id"

Ref: "classes"."_id" < "assignment"."_id"

Ref: "classes"."teacher_id" < "teacher"."__"

Ref: "users"."_id" < "transaction"."_id"

Ref: "courses"."_id" < "announcement"."_id"

Ref: "courses"."_id" < "review"."_id"

Ref: "student"."basket" < "basket_item"."__"

Ref: "student"."wishlist" < "wishlist_item"."__"

Ref: "student"."owned_progarms" < "owned_progarm_item"."__"

Ref: "courses"."_id" < "owned_progarm_item"."progarm_id"

Ref: "classes"."_id" < "owned_progarm_item"."progarm_id"

Ref: "post"."comments" < "comment"."__"

Ref: "transaction"."purchase_list" < "purchase_item"."__"

Ref: "post"."attachments" < "attached_file"."__"

Ref: "assignment"."attachments" < "attached_file"."__"

Ref: "pre_quiz"."quiz_id" - "quiz"."quiz_id"

Ref: "teacher"."owned_progarms" < "owned_progarm_item"."__"

Ref: "announcement"."attachments" < "attached_file2"."__"

Ref: "users"."config" - "config"."theme"

Ref: "chapters"."_id" < "lesson"."__"

Ref: "courses"."_id" < "chapters"."_id"

Ref: "course_progresses"."lessons" < "lesson_progress"."__"

Ref: "student"."__" < "course_progresses"."_id"
